### PR TITLE
Instructions to Upgrading To 1.1 are out-dated as Google API's has changed

### PR DESCRIPTION
**Pull request by ayumi-cloud**
See github issue: https://github.com/rainlab/googleanalytics-plugin/issues/102

@LukeTowers @daftspunk

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
Just tried to continue installation and notice that this plugin completely doesn't work with Google Analytics.

See my comment here: https://github.com/rainlab/googleanalytics-plugin/issues/101#issuecomment-727250601

Therefore the part:

```
The Profile ID number has also changed, follow these settings to find the new one:

1. In a new tab, navigate to the main [Google Analytics site](https://www.google.com/analytics/web/) and select the property you want to track.
1. Click the **Admin** main menu tab again and select **View > View Settings** from the menu. *Copy to your clipboard* the Profile ID (should be a number).
1. Paste this number in the **Analytics View/Profile ID number** field in the October back-end settings form.
```

Is completely wrong and doesn't exist anymore!

This plugin no longer works with Google Analytics.

**Comment by LukeTowers** [comment]
This plugin doesn't appear to work with Google Analytics 4, it still works just fine with universal analytics AFAIK. I'm personally not convinced at this time it's worth supporting Google Analytics 4, but that's probably just because I haven't used it yet. If Google's going to be heavily pushing GA4 down my throat then I'm going to be more closely evaluating competing products like Matomo

**Comment by ayumi-cloud** [comment]
The problem is we're using this plugin: https://octobercms.com/plugin/bedard-analyticsextension

> Before installing the Google Analytics Extension plugin, make sure your project already has the RainLab Google Analytics plugin installed and configured. Once this is done, you're ready to start creating your perfect dashboard. Here are some examples to get you started...

This allows GA to be displayed in the dashboard.

Google's moving all GA to version 4 (it's because GA3 and below don't fully pass GDPR). So they soon will turn off GA3.

Most people use and will continue to use GA, see below Analytics Usage Distribution in the Top 10 Million Sites:

Google Analytics Usage Statistics: 87.24%

Matomo Usage Statistics: 1.83%

**Comment by LukeTowers** [comment]
When exactly are they going to "turn off" universal analytics?

**Comment by ayumi-cloud** [comment]
@LukeTowers 

> When exactly are they going to "turn off" universal analytics?

From what I've seen so far doing some research, it seems like they are going to be turning off the following:

- Universal Analytics `Tracking ID` (which begins with "UA-") will be turned off and replaced with `Measurement ID` (which begins with "G-").

- `analytics.js` will be turned off and replaced with `gtag.js`

- `PROPERTY ID` seems to be removed and I can't find a replacement? Seems like it's changed to either `Measurement ID` or `STREAM ID`

- Measurement Protocol API has changed from v3 to v4. However, v4 is in `Aplha`, see here: , see here: https://developers.google.com/analytics/devguides/collection/protocol/ga4

- AMP-HTML `<amp-analytics>` now doesn't work at all and after an issue we opened Google added this pr: https://github.com/ampproject/amphtml/pull/31095/files

- Google's most popular Analytics extension / plugin for Google Analytics called: `AutoTrack`

image

They have turned off, see here: https://github.com/googleanalytics/autotrack/commit/646e079dbdad6dfb698d1fb4b5047d7edfcb07ef

- GDPR, in v3 the data didn't pass and in v4 various changes were automatically set.

Probably lots more things.

Universal Analytics versus Google Analytics 4 data: https://support.google.com/analytics/answer/9964640?hl=en

Google Analytics Release Logs: https://support.google.com/analytics/answer/9164320?hl=en&ref_topic=9143232

**Comment by ayumi-cloud** [comment]
Gonna answer your question and leave it in the issue, see here: https://github.com/rainlab/googleanalytics-plugin/issues/101#issuecomment-727970834 

I rather keep this pr related to just the `Google Developers Console` and not the `GA4` - to keep things tidy and in a single place.

**Comment by ayumi-cloud** [comment]
Gonna answer your question and leave it in the open ga4 github issue, see here: https://github.com/rainlab/googleanalytics-plugin/issues/101#issuecomment-727970834 

I rather keep this pr related to just the `Google Developers Console` and not the `GA4` - to keep things tidy and in separate places.

**Pull request closed without merging**
